### ISSUE TITLE
JQuery Version

### ISSUE THREAD

**Issue by maxbertinetti** [revig/revigniter#12]
### Summary

I read in the docs:

> The Jquery version currently supported is 1.4.2.

Is it true? It is not possible to use a modern (supported) version?

**Comment by revig** [comment]
Currently jQuery versions up to 1.8.3 should be compatible with revIgniter’s jQuery library. The development of jQuery is progressing so fast that it would require quite an effort to keep the library up to date, which is not justified given my impression that hardly anyone uses it. Now that I think about it the library should actually be marked as deprecated and then removed. I have already considered whether it wouldn't be better to develop a JavaScript library independent of jQuery.

**Comment by maxbertinetti** [comment]
The problem is with major version. JQuery is now on 3
